spring:
  application:
    name: iToken-springboot-admin
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.230.131:8761/eureka/,http://192.168.230.131:8861/eureka/,http://192.168.230.131:8961/eureka/